apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: artistry-cart-http-services
spec:
  selector:
    matchExpressions:
      - key: app.kubernetes.io/name
        operator: In
        values:
          - api-gateway
          - auth-service
          - product-service
          - order-service
          - recommendation-service
          - aivision-service
          - kafka-service
  podMetricsEndpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
      honorLabels: true
