apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: user-ui
spec:
  minReplicas: 2
  maxReplicas: 6
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: seller-ui
spec:
  minReplicas: 2
  maxReplicas: 6
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: api-gateway
spec:
  minReplicas: 2
  maxReplicas: 8
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: auth-service
spec:
  minReplicas: 2
  maxReplicas: 6
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: order-service
spec:
  minReplicas: 2
  maxReplicas: 6
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: recommendation-service
spec:
  minReplicas: 2
  maxReplicas: 5
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: aivision-service
spec:
  minReplicas: 2
  maxReplicas: 4
