apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: artistry-cart
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 50m
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - app.example.com
        - seller.example.com
        - api.example.com
      secretName: artistry-cart-tls
  rules:
    - host: app.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: user-ui
                port:
                  number: 3000
    - host: seller.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: seller-ui
                port:
                  number: 3001
    - host: api.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api-gateway
                port:
                  number: 8080
