apiVersion: v1
kind: Secret
metadata:
  name: artistry-cart-secrets
type: Opaque
stringData:
  DATABASE_URL: mongodb://username:password@mongodb.example.com:27017/artistry-cart
  REDIS_URL: redis://:password@redis.example.com:6379
  ACCESS_TOKEN_SECRET: replace-me
  REFRESH_TOKEN_SECRET: replace-me
  MAINTENANCE_TOKEN: replace-me
  STRIPE_SECRETE_KEY: replace-me
  STRIPE_WEBHOOK_SECRET: replace-me
  GOOGLE_CLIENT_ID: replace-me
  GOOGLE_CLIENT_SECRET: replace-me
  GITHUB_CLIENT_ID: replace-me
  GITHUB_CLIENT_SECRET: replace-me
  FACEBOOK_CLIENT_ID: replace-me
  FACEBOOK_CLIENT_SECRET: replace-me
  GOOGLE_API_KEY: replace-me
  HUGGINGFACE_API_KEY: replace-me
  IMAGEKIT_PUBLIC_API_KEY: replace-me
  IMAGEKIT_PRIVATE_API_KEY: replace-me
  IMAGEKIT_URL_ENDPOINT: https://ik.imagekit.io/replace-me
  KAFKA_SASL_USERNAME: replace-me
  KAFKA_SASL_PASSWORD: replace-me
  SMTP_USER: replace-me
  SMTP_PASS: replace-me
