apiVersion: v1
kind: ConfigMap
metadata:
  name: artistry-cart-platform-config
data:
  CORS_ALLOWED_ORIGINS: http://app.dev.artistry-cart.local,http://seller.dev.artistry-cart.local
  FRONTEND_URL: http://app.dev.artistry-cart.local
  NEXT_PUBLIC_SERVER_URI: http://api.dev.artistry-cart.local
  NEXT_PUBLIC_FRONTEND_URL: http://app.dev.artistry-cart.local
  NEXT_PUBLIC_USER_UI_LINK: http://app.dev.artistry-cart.local
  NEXT_PUBLIC_AI_VISION_API_URL: http://api.dev.artistry-cart.local/ai-vision/api/v1/ai
  OAUTH_REDIRECT_BASE_URL: http://api.dev.artistry-cart.local/auth
  KAFKA_BROKERS: kafka.dev.example.com:9092
  KAFKA_SSL: "false"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: artistry-cart
spec:
  tls:
    - hosts:
        - app.dev.artistry-cart.local
        - seller.dev.artistry-cart.local
        - api.dev.artistry-cart.local
      secretName: artistry-cart-dev-tls
  rules:
    - host: app.dev.artistry-cart.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: user-ui
                port:
                  number: 3000
    - host: seller.dev.artistry-cart.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: seller-ui
                port:
                  number: 3001
    - host: api.dev.artistry-cart.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api-gateway
                port:
                  number: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-ui
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: seller-ui
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendation-service
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aivision-service
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-service
spec:
  replicas: 1
